// frontends/vue/src/views/ArticleView.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { marked } from 'marked'
import { api } from '@/api'
import type { Article } from '@/types'
import { formatDate } from '@/utils/date'
import { useAuth } from '@/stores/auth'
import FollowButton from '@/components/FollowButton.vue'
import CommentSection from '@/components/CommentSection.vue'

const route = useRoute()
const router = useRouter()
const auth = useAuth()

const article = ref<Article | null>(null)
const following = ref(false)

const slug = computed(() => route.params.slug as string)
const isAuthor = computed(
  () => auth.user?.username === article.value?.author.username,
)

function renderMarkdown(text: string) {
  return marked.parse(text) as string
}

async function loadArticle() {
  try {
    const { article: fetched } = await api.getArticle(slug.value)
    article.value = fetched
    following.value = fetched.author.following
  } catch {
    router.replace('/')
  }
}

async function toggleFavorite() {
  if (!article.value || !auth.isAuthenticated) return
  const { article: updated } = article.value.favorited
    ? await api.unfavorite(article.value.slug)
    : await api.favorite(article.value.slug)
  article.value = updated
}

async function deleteArticle() {
  if (!article.value) return
  await api.deleteArticle(article.value.slug)
  router.push('/')
}

function onFollowUpdate(value: boolean) {
  following.value = value
  if (article.value) {
    article.value.author.following = value
  }
}

onMounted(loadArticle)
</script>

<template>
  <div v-if="article" class="article-page">
    <div class="banner">
      <div class="container">
        <h1>{{ article.title }}</h1>
        <div class="article-meta">
          <RouterLink :to="`/profile/${article.author.username}`">
            <img :src="article.author.image" />
          </RouterLink>
          <div class="info">
            <RouterLink :to="`/profile/${article.author.username}`" class="author">
              {{ article.author.username }}
            </RouterLink>
            <span class="date">{{ formatDate(article.createdAt) }}</span>
          </div>
          <FollowButton
            :username="article.author.username"
            :following="following"
            @update="onFollowUpdate"
          />
          &nbsp;&nbsp;
          <button
            v-if="auth.isAuthenticated && !isAuthor"
            class="btn btn-sm btn-outline-primary"
            @click.prevent="toggleFavorite"
          >
            <i class="ion-heart"></i>
            &nbsp; Favorite Post <span class="counter">({{ article.favoritesCount }})</span>
          </button>
          <RouterLink
            v-if="isAuthor"
            class="btn btn-sm btn-outline-secondary"
            :to="`/editor/${article.slug}`"
          >
            <i class="ion-edit"></i> Edit Article
          </RouterLink>
          <button
            v-if="isAuthor"
            class="btn btn-sm btn-outline-danger"
            @click.prevent="deleteArticle"
          >
            <i class="ion-trash-a"></i> Delete Article
          </button>
        </div>
      </div>
    </div>
    <div class="container page">
      <div class="row article-content">
        <div class="col-md-12">
          <div v-html="renderMarkdown(article.body)"></div>
          <ul class="tag-list">
            <li
              v-for="tag in article.tagList"
              :key="tag"
              class="tag-default tag-pill tag-outline"
            >
              {{ tag }}
            </li>
          </ul>
        </div>
      </div>
      <hr />
      <div class="article-actions">
        <div class="article-meta">
          <RouterLink :to="`/profile/${article.author.username}`">
            <img :src="article.author.image" />
          </RouterLink>
          <div class="info">
            <RouterLink :to="`/profile/${article.author.username}`" class="author">
              {{ article.author.username }}
            </RouterLink>
            <span class="date">{{ formatDate(article.createdAt) }}</span>
          </div>
          <FollowButton
            :username="article.author.username"
            :following="following"
            @update="onFollowUpdate"
          />
          &nbsp;
          <button
            v-if="auth.isAuthenticated && !isAuthor"
            class="btn btn-sm btn-outline-primary"
            @click.prevent="toggleFavorite"
          >
            <i class="ion-heart"></i>
            &nbsp; Favorite Article <span class="counter">({{ article.favoritesCount }})</span>
          </button>
          <RouterLink
            v-if="isAuthor"
            class="btn btn-sm btn-outline-secondary"
            :to="`/editor/${article.slug}`"
          >
            <i class="ion-edit"></i> Edit Article
          </RouterLink>
          <button
            v-if="isAuthor"
            class="btn btn-sm btn-outline-danger"
            @click.prevent="deleteArticle"
          >
            <i class="ion-trash-a"></i> Delete Article
          </button>
        </div>
      </div>
      <CommentSection :slug="slug" />
    </div>
  </div>
</template>

// frontends/svelte/src/views/ArticleView.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { marked } from 'marked'
  import { api } from '@/lib/api'
  import type { Article } from '@/lib/types'
  import { formatDate } from '@/lib/utils/date'
  import { auth } from '@/lib/auth.svelte'
  import { router, navigate, replace } from '@/lib/router.svelte'
  import FollowButton from '@/components/FollowButton.svelte'
  import CommentSection from '@/components/CommentSection.svelte'
  import RouterLink from '@/lib/RouterLink.svelte'

  let article = $state<Article | null>(null)
  let following = $state(false)

  const slug = $derived(router.route.params.slug)
  const isAuthor = $derived(auth.user?.username === article?.author.username)

  function renderMarkdown(text: string) {
    return marked.parse(text) as string
  }

  async function loadArticle() {
    try {
      const { article: fetched } = await api.getArticle(slug)
      article = fetched
      following = fetched.author.following
    } catch {
      replace('/')
    }
  }

  async function toggleFavorite() {
    if (!article || !auth.isAuthenticated) return
    const { article: updated } = article.favorited
      ? await api.unfavorite(article.slug)
      : await api.favorite(article.slug)
    article = updated
  }

  async function deleteArticle() {
    if (!article) return
    await api.deleteArticle(article.slug)
    navigate('/')
  }

  function onFollowUpdate(value: boolean) {
    following = value
    if (article) {
      article.author.following = value
    }
  }

  onMount(loadArticle)
</script>

{#if article}
  <div class="article-page">
    <div class="banner">
      <div class="container">
        <h1>{article.title}</h1>
        <div class="article-meta">
          <RouterLink href="/profile/{article.author.username}">
            <img src={article.author.image} alt="" />
          </RouterLink>
          <div class="info">
            <RouterLink href="/profile/{article.author.username}" class="author">
              {article.author.username}
            </RouterLink>
            <span class="date">{formatDate(article.createdAt)}</span>
          </div>
          <FollowButton username={article.author.username} {following} onupdate={onFollowUpdate} />
          &nbsp;&nbsp;
          {#if auth.isAuthenticated && !isAuthor}
            <button
              class="btn btn-sm btn-outline-primary"
              onclick={(e) => { e.preventDefault(); toggleFavorite() }}
            >
              <i class="ion-heart"></i>
              &nbsp; Favorite Post <span class="counter">({article.favoritesCount})</span>
            </button>
          {/if}
          {#if isAuthor}
            <RouterLink class="btn btn-sm btn-outline-secondary" href="/editor/{article.slug}">
              <i class="ion-edit"></i> Edit Article
            </RouterLink>
          {/if}
          {#if isAuthor}
            <button
              class="btn btn-sm btn-outline-danger"
              onclick={(e) => { e.preventDefault(); deleteArticle() }}
            >
              <i class="ion-trash-a"></i> Delete Article
            </button>
          {/if}
        </div>
      </div>
    </div>
    <div class="container page">
      <div class="row article-content">
        <div class="col-md-12">
          <div>{@html renderMarkdown(article.body)}</div>
          <ul class="tag-list">
            {#each article.tagList as tag (tag)}
              <li class="tag-default tag-pill tag-outline">{tag}</li>
            {/each}
          </ul>
        </div>
      </div>
      <hr />
      <div class="article-actions">
        <div class="article-meta">
          <RouterLink href="/profile/{article.author.username}">
            <img src={article.author.image} alt="" />
          </RouterLink>
          <div class="info">
            <RouterLink href="/profile/{article.author.username}" class="author">
              {article.author.username}
            </RouterLink>
            <span class="date">{formatDate(article.createdAt)}</span>
          </div>
          <FollowButton username={article.author.username} {following} onupdate={onFollowUpdate} />
          &nbsp;
          {#if auth.isAuthenticated && !isAuthor}
            <button
              class="btn btn-sm btn-outline-primary"
              onclick={(e) => { e.preventDefault(); toggleFavorite() }}
            >
              <i class="ion-heart"></i>
              &nbsp; Favorite Article <span class="counter">({article.favoritesCount})</span>
            </button>
          {/if}
          {#if isAuthor}
            <RouterLink class="btn btn-sm btn-outline-secondary" href="/editor/{article.slug}">
              <i class="ion-edit"></i> Edit Article
            </RouterLink>
          {/if}
          {#if isAuthor}
            <button
              class="btn btn-sm btn-outline-danger"
              onclick={(e) => { e.preventDefault(); deleteArticle() }}
            >
              <i class="ion-trash-a"></i> Delete Article
            </button>
          {/if}
        </div>
      </div>
      <CommentSection {slug} />
    </div>
  </div>
{/if}
