// frontends/vue/src/views/EditorView.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api, ApiError, formatErrors } from '@/api'
import { useAuth } from '@/stores/auth'

const route = useRoute()
const router = useRouter()
const auth = useAuth()

const isEdit = computed(() => !!route.params.slug)

const title = ref('')
const description = ref('')
const body = ref('')
const tagInput = ref('')
const tagList = ref<string[]>([])
const errors = ref<string[]>([])

onMounted(async () => {
  if (isEdit.value) {
    const slug = route.params.slug as string
    try {
      const { article } = await api.getArticle(slug)
      if (article.author.username !== auth.user?.username) {
        router.replace('/')
        return
      }
      title.value = article.title
      description.value = article.description
      body.value = article.body
      tagList.value = [...article.tagList]
    } catch {
      router.replace('/')
    }
  }
})

function addTag() {
  const tag = tagInput.value.trim()
  if (tag && !tagList.value.includes(tag)) {
    tagList.value.push(tag)
  }
  tagInput.value = ''
}

function removeTag(tag: string) {
  tagList.value = tagList.value.filter((t) => t !== tag)
}

function onTagKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter') {
    e.preventDefault()
    addTag()
  }
}

async function submit() {
  errors.value = []
  const articleData = {
    title: title.value,
    description: description.value,
    body: body.value,
    tagList: tagList.value,
  }
  try {
    if (isEdit.value) {
      const { article } = await api.updateArticle(route.params.slug as string, articleData)
      router.push(`/article/${article.slug}`)
    } else {
      const { article } = await api.createArticle(articleData)
      router.push(`/article/${article.slug}`)
    }
  } catch (e) {
    if (e instanceof ApiError) {
      errors.value = formatErrors(e.errors)
    }
  }
}
</script>

<template>
  <div class="editor-page">
    <div class="container page">
      <div class="row">
        <div class="col-md-10 offset-md-1 col-xs-12">
          <ul v-if="errors.length" class="error-messages">
            <li v-for="(err, i) in errors" :key="i">{{ err }}</li>
          </ul>
          <form @submit.prevent="submit">
            <fieldset>
              <fieldset class="form-group">
                <input
                  v-model="title"
                  type="text"
                  class="form-control form-control-lg"
                  placeholder="Article Title"
                />
              </fieldset>
              <fieldset class="form-group">
                <input
                  v-model="description"
                  type="text"
                  class="form-control"
                  placeholder="What's this article about?"
                />
              </fieldset>
              <fieldset class="form-group">
                <textarea
                  v-model="body"
                  class="form-control"
                  rows="8"
                  placeholder="Write your article (in markdown)"
                ></textarea>
              </fieldset>
              <fieldset class="form-group">
                <input
                  v-model="tagInput"
                  type="text"
                  class="form-control"
                  placeholder="Enter tags"
                  @keydown="onTagKeydown"
                />
                <div class="tag-list">
                  <span
                    v-for="tag in tagList"
                    :key="tag"
                    class="tag-default tag-pill"
                    @click="removeTag(tag)"
                  >
                    <i class="ion-close-round"></i> {{ tag }}
                  </span>
                </div>
              </fieldset>
              <button class="btn btn-lg pull-xs-right btn-primary" type="submit">
                Publish Article
              </button>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

// frontends/svelte/src/views/EditorView.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { api, ApiError, formatErrors } from '@/lib/api'
  import { auth } from '@/lib/auth.svelte'
  import { router, navigate, replace } from '@/lib/router.svelte'

  const isEdit = $derived(!!router.route.params.slug)

  let title = $state('')
  let description = $state('')
  let body = $state('')
  let tagInput = $state('')
  let tagList = $state<string[]>([])
  let errors = $state<string[]>([])

  onMount(async () => {
    if (isEdit) {
      const slug = router.route.params.slug
      try {
        const { article } = await api.getArticle(slug)
        if (article.author.username !== auth.user?.username) {
          replace('/')
          return
        }
        title = article.title
        description = article.description
        body = article.body
        tagList = [...article.tagList]
      } catch {
        replace('/')
      }
    }
  })

  function addTag() {
    const tag = tagInput.trim()
    if (tag && !tagList.includes(tag)) {
      tagList = [...tagList, tag]
    }
    tagInput = ''
  }

  function removeTag(tag: string) {
    tagList = tagList.filter((t) => t !== tag)
  }

  function onTagKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter') {
      e.preventDefault()
      addTag()
    }
  }

  async function submit() {
    errors = []
    const articleData = {
      title,
      description,
      body,
      tagList,
    }
    try {
      if (isEdit) {
        const { article } = await api.updateArticle(router.route.params.slug, articleData)
        navigate(`/article/${article.slug}`)
      } else {
        const { article } = await api.createArticle(articleData)
        navigate(`/article/${article.slug}`)
      }
    } catch (e) {
      if (e instanceof ApiError) {
        errors = formatErrors(e.errors)
      }
    }
  }
</script>

<div class="editor-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-10 offset-md-1 col-xs-12">
        {#if errors.length}
          <ul class="error-messages">
            {#each errors as err, i (i)}
              <li>{err}</li>
            {/each}
          </ul>
        {/if}
        <form onsubmit={(e) => { e.preventDefault(); submit() }}>
          <fieldset>
            <fieldset class="form-group">
              <input
                bind:value={title}
                type="text"
                class="form-control form-control-lg"
                placeholder="Article Title"
              />
            </fieldset>
            <fieldset class="form-group">
              <input
                bind:value={description}
                type="text"
                class="form-control"
                placeholder="What's this article about?"
              />
            </fieldset>
            <fieldset class="form-group">
              <textarea
                bind:value={body}
                class="form-control"
                rows="8"
                placeholder="Write your article (in markdown)"
              ></textarea>
            </fieldset>
            <fieldset class="form-group">
              <input
                bind:value={tagInput}
                type="text"
                class="form-control"
                placeholder="Enter tags"
                onkeydown={onTagKeydown}
              />
              <div class="tag-list">
                {#each tagList as tag (tag)}
                  <span class="tag-default tag-pill" onclick={() => removeTag(tag)}>
                    <i class="ion-close-round"></i> {tag}
                  </span>
                {/each}
              </div>
            </fieldset>
            <button class="btn btn-lg pull-xs-right btn-primary" type="submit">
              Publish Article
            </button>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>
