// frontends/angular/src/app/components/favorite-button/favorite-button.component.ts
import { Component, inject, input, output, signal } from '@angular/core';
import { ApiService } from '../../api/api.service';
import type { Article } from '../../api/api.types';
import { AuthService } from '../../core/auth.service';

@Component({
  selector: 'app-favorite-button',
  template: `
    @if (auth.isAuthenticated()) {
      <button
        type="button"
        class="btn btn-sm btn-outline-primary"
        [class.active]="article().favorited"
        [disabled]="busy()"
        (click)="toggleFavorite()"
      >
        <i class="ion-heart"></i>&nbsp;
        {{ article().favoritesCount }}
      </button>
    }
  `,
})
export class FavoriteButtonComponent {
  readonly article = input.required<Article>();
  readonly changed = output<Article>();

  readonly auth = inject(AuthService);
  private readonly api = inject(ApiService);

  readonly busy = signal(false);

  async toggleFavorite(): Promise<void> {
    if (this.busy()) {
      return;
    }

    this.busy.set(true);
    try {
      const current = this.article();
      const result = current.favorited
        ? await this.api.unfavoriteArticle(current.slug)
        : await this.api.favoriteArticle(current.slug);
      this.changed.emit(result.article);
    } finally {
      this.busy.set(false);
    }
  }
}

// frontends/next/components/FavoriteButton.tsx
'use client';

import { useState } from 'react';
import { api } from '@/lib/api/client';
import type { Article } from '@/lib/api/types';
import { useAuth } from '@/hooks/useAuth';

interface FavoriteButtonProps {
  article: Article;
  onChange?: (article: Article) => void;
}

export function FavoriteButton({ article, onChange }: FavoriteButtonProps) {
  const { isAuthenticated } = useAuth();
  const [busy, setBusy] = useState(false);

  if (!isAuthenticated) {
    return null;
  }

  async function toggleFavorite() {
    if (busy) {
      return;
    }
    setBusy(true);
    try {
      const result = article.favorited
        ? await api.unfavoriteArticle(article.slug)
        : await api.favoriteArticle(article.slug);
      onChange?.(result.article);
    } finally {
      setBusy(false);
    }
  }

  return (
    <button
      type="button"
      className={`btn btn-sm btn-outline-primary${article.favorited ? ' active' : ''}`}
      disabled={busy}
      onClick={toggleFavorite}
    >
      <i className="ion-heart"></i>&nbsp;
      {article.favoritesCount}
    </button>
  );
}
