// frontends/svelte/src/components/ArticleList.svelte
<script lang="ts">
  import type { Article } from '@/lib/types'
  import ArticlePreview from './ArticlePreview.svelte'
  import Pagination from './Pagination.svelte'

  interface Props {
    articles: Article[]
    total: number
    limit: number
    currentPage: number
    loading: boolean
    onpagechange?: (page: number) => void
    onupdate?: (article: Article) => void
  }

  let { articles, total, limit, currentPage, loading, onpagechange, onupdate }: Props = $props()
</script>

{#if loading}
  <div>Loading...</div>
{:else}
  {#if articles.length === 0}
    <div class="empty-feed-message">No articles are here... yet.</div>
  {/if}
  {#each articles as article (article.slug)}
    <ArticlePreview {article} {onupdate} />
  {/each}
  <Pagination {total} {limit} {currentPage} onpagechange={onpagechange} />
{/if}

// frontends/nuxt/app/components/ArticleList.vue
<script setup lang="ts">
import type { Article } from '~/types'

defineProps<{
  articles: Article[]
  total: number
  limit: number
  currentPage: number
  loading: boolean
}>()

const emit = defineEmits<{
  'page-change': [page: number]
  update: [article: Article]
}>()
</script>

<template>
  <div v-if="loading">Loading...</div>
  <template v-else>
    <div v-if="articles.length === 0" class="empty-feed-message">No articles are here... yet.</div>
    <ArticlePreview
      v-for="article in articles"
      :key="article.slug"
      :article="article"
      @update="emit('update', $event)"
    />
    <Pagination
      :total="total"
      :limit="limit"
      :current-page="currentPage"
      @page-change="emit('page-change', $event)"
    />
  </template>
</template>
