// frontends/svelte/src/components/Pagination.svelte
<script lang="ts">
  interface Props {
    total: number
    limit: number
    currentPage: number
    onpagechange?: (page: number) => void
  }

  let { total, limit, currentPage, onpagechange }: Props = $props()

  const totalPages = $derived(Math.ceil(total / limit))

  function goTo(page: number) {
    if (page >= 1 && page <= totalPages && page !== currentPage) {
      onpagechange?.(page)
    }
  }
</script>

{#if totalPages > 1}
  <ul class="pagination">
    {#each Array.from({ length: totalPages }, (_, i) => i + 1) as page (page)}
      <li class="page-item" class:active={page === currentPage}>
        <a class="page-link" href="" onclick={(e) => { e.preventDefault(); goTo(page) }}>{page}</a>
      </li>
    {/each}
  </ul>
{/if}

// frontends/vue/src/components/Pagination.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  total: number
  limit: number
  currentPage: number
}>()

const emit = defineEmits<{
  'page-change': [page: number]
}>()

const totalPages = computed(() => Math.ceil(props.total / props.limit))

function goTo(page: number) {
  if (page >= 1 && page <= totalPages.value && page !== props.currentPage) {
    emit('page-change', page)
  }
}
</script>

<template>
  <ul v-if="totalPages > 1" class="pagination">
    <li
      v-for="page in totalPages"
      :key="page"
      class="page-item"
      :class="{ active: page === currentPage }"
    >
      <a class="page-link" href="" @click.prevent="goTo(page)">{{ page }}</a>
    </li>
  </ul>
</template>
