// frontends/vue/src/components/AppHeader.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { useAuth } from '@/stores/auth'

const route = useRoute()
const auth = useAuth()

const isHome = computed(() => route.path === '/')
const isLogin = computed(() => route.path === '/login')
const isRegister = computed(() => route.path === '/register')
const isSettings = computed(() => route.path === '/settings')
const isEditor = computed(() => route.path.startsWith('/editor'))
</script>

<template>
  <nav class="navbar navbar-light">
    <div class="container">
      <RouterLink class="navbar-brand" to="/">conduit</RouterLink>
      <ul class="nav navbar-nav pull-xs-right">
        <template v-if="auth.isAuthenticated && auth.user">
          <li class="nav-item">
            <RouterLink class="nav-link" :class="{ active: isHome }" to="/">
              Home
            </RouterLink>
          </li>
          <li class="nav-item">
            <RouterLink class="nav-link" :class="{ active: isEditor }" to="/editor">
              <i class="ion-compose"></i>&nbsp;New Article
            </RouterLink>
          </li>
          <li class="nav-item">
            <RouterLink class="nav-link" :class="{ active: isSettings }" to="/settings">
              <i class="ion-gear-a"></i>&nbsp;Settings
            </RouterLink>
          </li>
          <li class="nav-item">
            <RouterLink
              class="nav-link"
              :class="{ active: route.path === `/profile/${auth.user.username}` }"
              :to="`/profile/${auth.user.username}`"
            >
              <img :src="auth.user.image" class="user-pic" />
              {{ auth.user.username }}
            </RouterLink>
          </li>
        </template>
        <template v-else>
          <li class="nav-item">
            <RouterLink class="nav-link" :class="{ active: isHome }" to="/">
              Home
            </RouterLink>
          </li>
          <li class="nav-item">
            <RouterLink class="nav-link" :class="{ active: isLogin }" to="/login">
              Sign in
            </RouterLink>
          </li>
          <li class="nav-item">
            <RouterLink class="nav-link" :class="{ active: isRegister }" to="/register">
              Sign up
            </RouterLink>
          </li>
        </template>
      </ul>
    </div>
  </nav>
</template>

// frontends/svelte/src/components/AppHeader.svelte
<script lang="ts">
  import RouterLink from '@/lib/RouterLink.svelte'
  import { router } from '@/lib/router.svelte'
  import { auth } from '@/lib/auth.svelte'
</script>

<nav class="navbar navbar-light">
  <div class="container">
    <RouterLink class="navbar-brand" href="/">conduit</RouterLink>
    <ul class="nav navbar-nav pull-xs-right">
      {#if auth.isAuthenticated && auth.user}
        <li class="nav-item">
          <RouterLink class="nav-link" href="/" active={router.route.path === '/'}>
            Home
          </RouterLink>
        </li>
        <li class="nav-item">
          <RouterLink class="nav-link" href="/editor" active={router.route.path.startsWith('/editor')}>
            <i class="ion-compose"></i>&nbsp;New Article
          </RouterLink>
        </li>
        <li class="nav-item">
          <RouterLink class="nav-link" href="/settings" active={router.route.path === '/settings'}>
            <i class="ion-gear-a"></i>&nbsp;Settings
          </RouterLink>
        </li>
        <li class="nav-item">
          <RouterLink
            class="nav-link"
            href="/profile/{auth.user.username}"
            active={router.route.path === `/profile/${auth.user.username}`}
          >
            <img src={auth.user.image} class="user-pic" alt="" />
            {auth.user.username}
          </RouterLink>
        </li>
      {:else}
        <li class="nav-item">
          <RouterLink class="nav-link" href="/" active={router.route.path === '/'}>
            Home
          </RouterLink>
        </li>
        <li class="nav-item">
          <RouterLink class="nav-link" href="/login" active={router.route.path === '/login'}>
            Sign in
          </RouterLink>
        </li>
        <li class="nav-item">
          <RouterLink class="nav-link" href="/register" active={router.route.path === '/register'}>
            Sign up
          </RouterLink>
        </li>
      {/if}
    </ul>
  </div>
</nav>
