// frontends/vue/src/components/ArticleMeta.vue
<script setup lang="ts">
import type { Article } from '@/types'
import { formatDate } from '@/utils/date'
import FavoriteButton from './FavoriteButton.vue'

defineProps<{
  article: Article
  hideFavorite?: boolean
}>()

const emit = defineEmits<{
  update: [article: Article]
}>()
</script>

<template>
  <div class="article-meta">
    <RouterLink :to="`/profile/${article.author.username}`">
      <img :src="article.author.image" />
    </RouterLink>
    <div class="info">
      <RouterLink :to="`/profile/${article.author.username}`" class="author">
        {{ article.author.username }}
      </RouterLink>
      <span class="date">{{ formatDate(article.createdAt) }}</span>
    </div>
    <FavoriteButton
      v-if="!hideFavorite"
      :article="article"
      @update="emit('update', $event)"
    />
  </div>
</template>

// frontends/svelte/src/components/ArticleMeta.svelte
<script lang="ts">
  import type { Article } from '@/lib/types'
  import { formatDate } from '@/lib/utils/date'
  import FavoriteButton from './FavoriteButton.svelte'
  import RouterLink from '@/lib/RouterLink.svelte'

  interface Props {
    article: Article
    hideFavorite?: boolean
    onupdate?: (article: Article) => void
  }

  let { article, hideFavorite = false, onupdate }: Props = $props()
</script>

<div class="article-meta">
  <RouterLink href="/profile/{article.author.username}">
    <img src={article.author.image} alt="" />
  </RouterLink>
  <div class="info">
    <RouterLink href="/profile/{article.author.username}" class="author">
      {article.author.username}
    </RouterLink>
    <span class="date">{formatDate(article.createdAt)}</span>
  </div>
  {#if !hideFavorite}
    <FavoriteButton {article} {onupdate} />
  {/if}
</div>
