// frontends/next/components/ArticleMeta.tsx
import Link from 'next/link';
import type { Article } from '@/lib/api/types';
import { formatDate } from '@/lib/formatDate';
import { FavoriteButton } from './FavoriteButton';

interface ArticleMetaProps {
  article: Article;
  onFavoriteChange?: (article: Article) => void;
}

export function ArticleMeta({ article, onFavoriteChange }: ArticleMetaProps) {
  return (
    <div className="article-meta">
      <Link href={`/profile/${article.author.username}`}>
        <img src={article.author.image} alt="" />
      </Link>
      <div className="info">
        <Link href={`/profile/${article.author.username}`} className="author">
          {article.author.username}
        </Link>
        <span className="date">{formatDate(article.createdAt)}</span>
      </div>
      <FavoriteButton article={article} onChange={onFavoriteChange} />
    </div>
  );
}

// frontends/svelte/src/components/ArticleMeta.svelte
<script lang="ts">
  import type { Article } from '@/lib/types'
  import { formatDate } from '@/lib/utils/date'
  import FavoriteButton from './FavoriteButton.svelte'
  import RouterLink from '@/lib/RouterLink.svelte'

  interface Props {
    article: Article
    hideFavorite?: boolean
    onupdate?: (article: Article) => void
  }

  let { article, hideFavorite = false, onupdate }: Props = $props()
</script>

<div class="article-meta">
  <RouterLink href="/profile/{article.author.username}">
    <img src={article.author.image} alt="" />
  </RouterLink>
  <div class="info">
    <RouterLink href="/profile/{article.author.username}" class="author">
      {article.author.username}
    </RouterLink>
    <span class="date">{formatDate(article.createdAt)}</span>
  </div>
  {#if !hideFavorite}
    <FavoriteButton {article} {onupdate} />
  {/if}
</div>
