// frontends/nuxt/app/components/FavoriteButton.vue
<script setup lang="ts">
import type { Article } from '~/types'

const props = defineProps<{
  article: Article
}>()

const emit = defineEmits<{
  update: [article: Article]
}>()

const auth = useAuth()
const api = useApi()

const isFavorited = computed(() => props.article.favorited)
const count = computed(() => props.article.favoritesCount)

async function toggle() {
  if (!auth.isAuthenticated.value) return
  const { article } = isFavorited.value
    ? await api.unfavorite(props.article.slug)
    : await api.favorite(props.article.slug)
  emit('update', article)
}
</script>

<template>
  <button
    v-if="auth.isAuthenticated.value"
    class="btn btn-outline-primary btn-sm pull-xs-right"
    :class="{ active: isFavorited }"
    @click.prevent="toggle"
  >
    <i class="ion-heart"></i> {{ count }}
  </button>
</template>

// frontends/svelte/src/components/FavoriteButton.svelte
<script lang="ts">
  import type { Article } from '@/lib/types'
  import { api } from '@/lib/api'
  import { auth } from '@/lib/auth.svelte'

  interface Props {
    article: Article
    onupdate?: (article: Article) => void
  }

  let { article, onupdate }: Props = $props()

  async function toggle() {
    if (!auth.isAuthenticated) return
    const { article: updated } = article.favorited
      ? await api.unfavorite(article.slug)
      : await api.favorite(article.slug)
    onupdate?.(updated)
  }
</script>

{#if auth.isAuthenticated}
  <button
    class="btn btn-outline-primary btn-sm pull-xs-right"
    class:active={article.favorited}
    onclick={(e) => { e.preventDefault(); toggle() }}
  >
    <i class="ion-heart"></i> {article.favoritesCount}
  </button>
{/if}
