// frontends/nuxt/app/components/FollowButton.vue
<script setup lang="ts">
const props = defineProps<{
  username: string
  following: boolean
}>()

const emit = defineEmits<{
  update: [following: boolean]
}>()

const auth = useAuth()
const api = useApi()

async function toggle() {
  if (!auth.isAuthenticated.value) return
  const { profile } = props.following
    ? await api.unfollow(props.username)
    : await api.follow(props.username)
  emit('update', profile.following)
}
</script>

<template>
  <button
    v-if="auth.isAuthenticated.value && auth.user.value?.username !== username"
    class="btn btn-sm btn-outline-secondary action-btn"
    @click.prevent="toggle"
  >
    <i :class="following ? 'ion-minus-round' : 'ion-plus-round'"></i>
    &nbsp; {{ following ? 'Unfollow' : 'Follow' }} {{ username }}
  </button>
</template>

// frontends/svelte/src/components/FollowButton.svelte
<script lang="ts">
  import { api } from '@/lib/api'
  import { auth } from '@/lib/auth.svelte'

  interface Props {
    username: string
    following: boolean
    onupdate?: (following: boolean) => void
  }

  let { username, following, onupdate }: Props = $props()

  async function toggle() {
    if (!auth.isAuthenticated) return
    const { profile } = following
      ? await api.unfollow(username)
      : await api.follow(username)
    onupdate?.(profile.following)
  }
</script>

{#if auth.isAuthenticated && auth.user?.username !== username}
  <button
    class="btn btn-sm btn-outline-secondary action-btn"
    onclick={(e) => { e.preventDefault(); toggle() }}
  >
    <i class={following ? 'ion-minus-round' : 'ion-plus-round'}></i>
    &nbsp; {following ? 'Unfollow' : 'Follow'} {username}
  </button>
{/if}
