// frontends/angular/src/app/components/error-messages/error-messages.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-error-messages',
  template: `
    @if (errors().length > 0) {
      <ul class="error-messages">
        @for (error of errors(); track error) {
          <li>{{ error }}</li>
        }
      </ul>
    }
  `,
})
export class ErrorMessagesComponent {
  readonly errors = input<string[]>([]);
}

// frontends/react/src/components/ErrorMessages.tsx
interface ErrorMessagesProps {
  errors: string[];
}

export function ErrorMessages({ errors }: ErrorMessagesProps) {
  if (errors.length === 0) {
    return null;
  }

  return (
    <ul className="error-messages">
      {errors.map((error) => (
        <li key={error}>{error}</li>
      ))}
    </ul>
  );
}
