// frontends/angular/src/app/components/pagination/pagination.component.ts
import { Component, input, output } from '@angular/core';

@Component({
  selector: 'app-pagination',
  template: `
    @if (totalPages() > 1) {
      <ul class="pagination">
        <li class="page-item" [class.disabled]="page() === 1">
          <button
            type="button"
            class="page-link"
            [disabled]="page() === 1"
            (click)="pageChange.emit(page() - 1)"
          >
            &laquo; Previous
          </button>
        </li>
        @for (n of pages(); track n) {
          <li class="page-item" [class.active]="page() === n">
            <button type="button" class="page-link" (click)="pageChange.emit(n)">
              {{ n }}
            </button>
          </li>
        }
        <li class="page-item" [class.disabled]="page() === totalPages()">
          <button
            type="button"
            class="page-link"
            [disabled]="page() === totalPages()"
            (click)="pageChange.emit(page() + 1)"
          >
            Next &raquo;
          </button>
        </li>
      </ul>
    }
  `,
})
export class PaginationComponent {
  readonly page = input(1);
  readonly totalPages = input(1);
  readonly pageChange = output<number>();

  pages = () => Array.from({ length: this.totalPages() }, (_, i) => i + 1);
}

// frontends/react/src/components/Pagination.tsx
interface PaginationProps {
  page: number;
  totalPages: number;
  onPageChange: (page: number) => void;
}

export function Pagination({ page, totalPages, onPageChange }: PaginationProps) {
  if (totalPages <= 1) {
    return null;
  }

  const pages = Array.from({ length: totalPages }, (_, i) => i + 1);

  return (
    <ul className="pagination">
      <li className={`page-item${page === 1 ? ' disabled' : ''}`}>
        <button
          type="button"
          className="page-link"
          disabled={page === 1}
          onClick={() => onPageChange(page - 1)}
        >
          &laquo; Previous
        </button>
      </li>
      {pages.map((n) => (
        <li key={n} className={`page-item${page === n ? ' active' : ''}`}>
          <button type="button" className="page-link" onClick={() => onPageChange(n)}>
            {n}
          </button>
        </li>
      ))}
      <li className={`page-item${page === totalPages ? ' disabled' : ''}`}>
        <button
          type="button"
          className="page-link"
          disabled={page === totalPages}
          onClick={() => onPageChange(page + 1)}
        >
          Next &raquo;
        </button>
      </li>
    </ul>
  );
}
