// frontends/angular/src/app/components/tag-list/tag-list.component.ts
import { Component, inject, input } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';

@Component({
  selector: 'app-tag-list',
  imports: [RouterLink],
  template: `
    <div class="sidebar">
      <p>Popular Tags</p>
      <div class="tag-list">
        @for (tag of tags(); track tag) {
          <a
            class="tag-pill tag-default"
            [class.active]="activeTag() === tag"
            [routerLink]="['/']"
            [queryParams]="buildTagParams(tag)"
          >
            {{ tag }}
          </a>
        }
      </div>
    </div>
  `,
})
export class TagListComponent {
  readonly tags = input<string[]>([]);
  readonly activeTag = input<string | undefined>();

  private readonly route = inject(ActivatedRoute);

  buildTagParams(tag: string): Record<string, string> {
    const params: Record<string, string> = {};
    const limit = this.route.snapshot.queryParamMap.get('limit');
    if (limit) {
      params['limit'] = limit;
    }
    if (this.activeTag() !== tag) {
      params['tag'] = tag;
    }
    return params;
  }
}

// frontends/react/src/components/TagList.tsx
import { Link, useSearchParams } from 'react-router';

interface TagListProps {
  tags: string[];
  activeTag?: string;
}

export function TagList({ tags, activeTag }: TagListProps) {
  const [searchParams] = useSearchParams();
  const limit = searchParams.get('limit');

  function buildTagUrl(tag: string): string {
    const params = new URLSearchParams();
    if (limit) {
      params.set('limit', limit);
    }
    if (activeTag !== tag) {
      params.set('tag', tag);
    }
    const qs = params.toString();
    return qs ? `/?${qs}` : '/';
  }

  return (
    <div className="sidebar">
      <p>Popular Tags</p>
      <div className="tag-list">
        {tags.map((tag) => (
          <Link
            key={tag}
            to={buildTagUrl(tag)}
            className={`tag-pill tag-default${activeTag === tag ? ' active' : ''}`}
          >
            {tag}
          </Link>
        ))}
      </div>
    </div>
  );
}
